import { NextResponse } from 'next/server';
import { db } from '@/prisma/db';
import { getSession } from '@/lib/auth/session';

function generatePrintableHtml(report: any): string {
  const incident = report.incident;
  const timeline = report.timeline || [];
  const notes = report.notes || [];
  const recommendations = report.remediationRecommendations || [];
  
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Incident Investigation Report - ${incident.id}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #333;
      background-color: #fff;
      line-height: 1.6;
      padding: 40px;
    }
    .header {
      border-bottom: 2px solid #000;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .title {
      font-size: 28px;
      font-weight: bold;
      color: #111;
      margin: 0;
    }
    .meta-grid {
      display: grid;
      grid-template-cols: 1fr 1fr;
      gap: 15px;
      margin-top: 20px;
      font-size: 14px;
    }
    .meta-item span {
      font-weight: bold;
      color: #555;
    }
    .severity-badge {
      display: inline-block;
      padding: 3px 8px;
      border-radius: 4px;
      font-weight: bold;
      font-size: 12px;
      text-transform: uppercase;
      border: 1px solid #ddd;
    }
    .severity-CRITICAL { background-color: #ffeef0; color: #d73a49; border-color: #f9c2c9; }
    .severity-HIGH { background-color: #fff5eb; color: #e36209; border-color: #fcd7b6; }
    .severity-MEDIUM { background-color: #fffdf5; color: #b07d00; border-color: #fff1c2; }
    .severity-LOW { background-color: #f6f8fa; color: #586069; border-color: #eaecef; }
    
    .section-title {
      font-size: 18px;
      font-weight: bold;
      border-bottom: 1px solid #ddd;
      padding-bottom: 8px;
      margin-top: 30px;
      margin-bottom: 15px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .description {
      background-color: #f8f9fa;
      border-left: 4px solid #0056b3;
      padding: 15px;
      font-size: 14px;
      white-space: pre-wrap;
    }
    .list-item {
      margin-bottom: 10px;
      font-size: 14px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
      margin-bottom: 20px;
    }
    th, td {
      border: 1px solid #ddd;
      padding: 10px;
      text-align: left;
      font-size: 13px;
    }
    th {
      background-color: #f2f2f2;
      font-weight: bold;
    }
    .footer {
      margin-top: 50px;
      border-top: 1px solid #ddd;
      padding-top: 20px;
      text-align: center;
      font-size: 12px;
      color: #777;
    }
    .print-button {
      background-color: #0056b3;
      color: #fff;
      border: none;
      padding: 10px 20px;
      font-size: 14px;
      font-weight: bold;
      border-radius: 4px;
      cursor: pointer;
      margin-bottom: 20px;
    }
    @media print {
      .print-button {
        display: none;
      }
      body {
        padding: 0;
      }
    }
  </style>
</head>
<body>
  <button class="print-button" onclick="window.print()">Print / Save as PDF</button>
  
  <div class="header">
    <div class="title">${incident.title}</div>
    <div style="margin-top: 5px; color: #666; font-size: 14px;">Incident Investigation Report</div>
    
    <div class="meta-grid">
      <div class="meta-item"><span>Incident ID:</span> ${incident.id}</div>
      <div class="meta-item"><span>Severity:</span> <span class="severity-badge severity-${incident.severity}">${incident.severity}</span></div>
      <div class="meta-item"><span>Category:</span> ${incident.category}</div>
      <div class="meta-item"><span>Status:</span> ${incident.status}</div>
      <div class="meta-item"><span>Source IP:</span> ${incident.sourceIp || 'N/A'}</div>
      <div class="meta-item"><span>Destination IP:</span> ${incident.destIp || 'N/A'}</div>
      <div class="meta-item"><span>Created At:</span> ${new Date(incident.createdAt).toLocaleString()}</div>
      <div class="meta-item"><span>Assigned Analyst:</span> ${incident.assignedTo}</div>
      <div class="meta-item"><span>Report Generated:</span> ${new Date(report.generatedAt).toLocaleString()}</div>
      <div class="meta-item"><span>Generated By:</span> ${report.generatedBy}</div>
    </div>
  </div>

  <div class="section-title">Findings / Description</div>
  <div class="description">${incident.description}</div>

  ${incident.detectionRule ? `
  <div class="section-title">Detection Rule Details</div>
  <table>
    <tr><th>Rule Name</th><td>${incident.detectionRule.name}</td></tr>
    <tr><th>Mitre ATT&CK ID</th><td>${incident.detectionRule.mitreAttack}</td></tr>
    <tr><th>Rule Severity</th><td>${incident.detectionRule.severity}</td></tr>
    <tr><th>Rule Query Logic</th><td><code>${incident.detectionRule.query}</code></td></tr>
  </table>
  ` : ''}

  <div class="section-title">Remediation & Action Plan</div>
  <ul>
    ${recommendations.map((rec: string) => `<li class="list-item">${rec}</li>`).join('')}
  </ul>

  <div class="section-title">Analyst Notes Log</div>
  ${notes.length === 0 ? '<p style="font-size: 14px; font-style: italic;">No notes recorded.</p>' : `
  <table style="width: 100%;">
    <thead>
      <tr>
        <th style="width: 25%;">Author / Time</th>
        <th style="width: 75%;">Note Details</th>
      </tr>
    </thead>
    <tbody>
      ${notes.map((n: any) => `
        <tr>
          <td><strong>${n.authorName}</strong><br><span style="font-size: 11px; color:#666;">${new Date(n.createdAt).toLocaleString()}</span></td>
          <td>${n.content}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  `}

  <div class="section-title">Audit Log Ingestion Timeline</div>
  <table style="width: 100%;">
    <thead>
      <tr>
        <th style="width: 25%;">Timestamp</th>
        <th style="width: 25%;">Event Title</th>
        <th style="width: 35%;">Description</th>
        <th style="width: 15%;">Source</th>
      </tr>
    </thead>
    <tbody>
      ${timeline.map((t: any) => `
        <tr>
          <td>${new Date(t.eventTime).toLocaleString()}</td>
          <td><strong>${t.title}</strong></td>
          <td>${t.description}</td>
          <td><span style="font-family: monospace; font-size: 11px;">${t.source}</span></td>
        </tr>
      `).join('')}
    </tbody>
  </table>

  <div class="footer">
    TraceGuard Security Operations Center Dashboard • Confidential Document
  </div>
</body>
</html>`;
}

function getRecommendations(category: string, severity: string): string[] {
  const common = [
    'Ensure host logs and local audit configurations are archived safely.',
    'Inform executive staff of critical response milestones.',
    'Update firewall block rules with verified adversary IPs if available.'
  ];

  if (category.toLowerCase().includes('credential') || category.toLowerCase().includes('brute')) {
    return [
      'Revoke session tokens and force password reset for affected identities.',
      'Audit Active Directory / MFA prompt attempts from the source IP.',
      'Implement firewall rules limiting SSH/RDP ingress to trusted subnets only.',
      ...common
    ];
  }

  if (category.toLowerCase().includes('ransomware') || category.toLowerCase().includes('command')) {
    return [
      'Isolate the target machine immediately from the core VLAN to prevent lateral infection.',
      'Examine memory buffer and capture current process heap dump if possible.',
      'Check system backups and verify backup repository integrity.',
      ...common
    ];
  }

  if (category.toLowerCase().includes('exfiltration') || category.toLowerCase().includes('dns')) {
    return [
      'Verify external outbound volumes and identify target destination endpoints.',
      'Block target exfiltration domain at the root DNS resolver.',
      'Run complete full disk antivirus scanning on target research host.',
      ...common
    ];
  }

  return [
    'Monitor host activities for subsequent alerts or secondary alerts.',
    'Validate event signatures against known threat intelligence references.',
    ...common
  ];
}

async function buildReportData(incidentId: string | null, sessionName: string) {
  const incidents = await db.orm.public.Incident.all();
  const rules = await db.orm.public.DetectionRule.all();
  const users = await db.orm.public.User.all();

  if (incidentId) {
    const incident = incidents.find(i => i.id === incidentId);
    if (!incident) return null;

    const assignedTo = users.find(u => u.id === incident.assignedToId);
    const rule = rules.find(r => r.id === incident.ruleId);
    const notes = await db.orm.public.Note.where({ incidentId }).all();
    const timeline = await db.orm.public.EventTimeline.where({ incidentId }).all();

    const notesWithAuthors = notes.map(n => {
      const author = users.find(u => u.id === n.userId);
      return {
        ...n,
        authorName: author ? author.name : 'Unknown'
      };
    });

    return {
      reportType: 'Detailed Incident Investigation Report',
      generatedAt: new Date().toISOString(),
      generatedBy: sessionName,
      incident: {
        id: incident.id,
        title: incident.title,
        description: incident.description,
        status: incident.status,
        severity: incident.severity,
        category: incident.category,
        sourceIp: incident.sourceIp,
        destIp: incident.destIp,
        createdAt: incident.createdAt,
        updatedAt: incident.updatedAt,
        assignedTo: assignedTo ? assignedTo.name : 'Unassigned',
        detectionRule: rule ? {
          name: rule.name,
          mitreAttack: rule.mitreAttack,
          severity: rule.severity,
          query: rule.query
        } : null,
      },
      timeline: timeline.sort((a, b) => new Date(a.eventTime).getTime() - new Date(b.eventTime).getTime()),
      notes: notesWithAuthors,
      remediationRecommendations: getRecommendations(incident.category, incident.severity)
    };
  } else {
    // Global SOC Dashboard Metrics Report
    const totalIncidents = incidents.length;
    const statusCounts = incidents.reduce((acc: Record<string, number>, curr) => {
      acc[curr.status] = (acc[curr.status] || 0) + 1;
      return acc;
    }, {});
    const severityCounts = incidents.reduce((acc: Record<string, number>, curr) => {
      acc[curr.severity] = (acc[curr.severity] || 0) + 1;
      return acc;
    }, {});

    return {
      reportType: 'SOC Performance and Queue Status Report',
      generatedAt: new Date().toISOString(),
      generatedBy: sessionName,
      metrics: {
        totalIncidents,
        statusDistribution: statusCounts,
        severityDistribution: severityCounts,
        unassignedIncidents: incidents.filter(i => !i.assignedToId).length,
        investigatingIncidents: incidents.filter(i => i.status === 'INVESTIGATING').length,
        resolvedIncidents: incidents.filter(i => i.status === 'RESOLVED').length
      },
      recentCriticalIncidents: incidents
        .filter(i => i.severity === 'CRITICAL' || i.severity === 'HIGH')
        .slice(0, 5)
        .map(i => ({
          id: i.id,
          title: i.title,
          status: i.status,
          severity: i.severity,
          createdAt: i.createdAt
        }))
    };
  }
}

export async function GET(request: Request) {
  try {
    const session = await getSession();
    if (!session) {
      return new Response('Unauthorized', { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const incidentId = searchParams.get('incidentId');
    const format = searchParams.get('format');

    // Create Audit Log
    await db.orm.public.AuditLog.create({
      id: `audit-${crypto.randomUUID()}`,
      userId: session.userId,
      action: 'GENERATE_REPORT',
      details: incidentId ? `Viewed printable report for incident ${incidentId}` : 'Viewed printable global SOC metrics report',
      ipAddress: request.headers.get('x-forwarded-for') || '127.0.0.1',
      createdAt: new Date().toISOString(),
    });

    const report = await buildReportData(incidentId, session.name);
    if (!report) {
      return new Response('Incident not found', { status: 404 });
    }

    if (format === 'html') {
      const htmlContent = generatePrintableHtml(report);
      return new Response(htmlContent, {
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      });
    }

    return NextResponse.json(report);
  } catch (error) {
    console.error('Failed to generate report (GET):', error);
    return new Response('Internal Server Error', { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const session = await getSession();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const body = await request.json();
    const { incidentId, format } = body;

    // Create Audit Log
    await db.orm.public.AuditLog.create({
      id: `audit-${crypto.randomUUID()}`,
      userId: session.userId,
      action: 'GENERATE_REPORT',
      details: incidentId ? `Generated detailed incident report for ${incidentId}` : 'Generated global SOC metrics report',
      ipAddress: request.headers.get('x-forwarded-for') || '127.0.0.1',
      createdAt: new Date().toISOString(),
    });

    const report = await buildReportData(incidentId, session.name);
    if (!report) {
      return NextResponse.json({ error: 'Incident not found' }, { status: 404 });
    }

    if (format === 'html') {
      const htmlContent = generatePrintableHtml(report);
      return new Response(htmlContent, {
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      });
    }

    return NextResponse.json(report);
  } catch (error) {
    console.error('Failed to generate report (POST):', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
